name: Quality Assurance CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    types: [ "closed" ]
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]
        operating-system: ['ubuntu-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install --prefer-source --no-interaction --dev
      - name: Coding Standard
        run: composer run dev:lint:style
      - name: Static Code Analysis
        run: composer run dev:analyze
      - name: Run test suite
        run: composer run dev:test:phpunit